# filename: .github/workflows/databricks-free-edition-poc.yml
name: Databricks Free Edition POC

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

permissions:
  contents: read

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  validate:
    runs-on: ubuntu-latest
    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Databricks CLI
        uses: databricks/setup-cli@main

      - name: Validate bundle
        working-directory: ./path-to-your-bundle
        run: databricks bundle validate -t dev

  deploy-dev:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Databricks CLI
        uses: databricks/setup-cli@main

      - name: Validate bundle
        working-directory: /Workspace/Users/gopatwadv@gmail.com/POC/dabpoc/dabproject/databricks.yml
        run: databricks bundle validate -t dev

      - name: Deploy bundle
        working-directory: ./path-to-your-bundle
        run: databricks bundle deploy -t dev
